data "aws_region" "current" {}

# Outputs a backend configuration file that can be used in a `terraform init`
# command by passing the argument `-backend-config=<config_output_path>` for
# configurations leveraging this backend. See
# https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration
# for details on using these settings with partial configurations.
resource "local_file" "backend_config" {
  count = var.config_output_path != "" ? 1 : 0

  filename             = var.config_output_path
  directory_permission = "0755"
  file_permission      = "0644"
  content              = <<-EOT
    # Autogenerated by the s3_terraform_backend module, do not modify this file
    region         = "${data.aws_region.current.name}"
    bucket         = "${aws_s3_bucket.tfstate.id}"
    dynamodb_table = "${aws_dynamodb_table.terraform_lock.name}"
    %{if var.profile != ""}profile        = "${var.profile}"%{endif}
  EOT
}
